name: Update this repo's README

# on:
#   schedule:
#     # Once a day at 8 AM
#     - cron: 0 8 * * *
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Why are you running ?'
        required: false
        default: 'Test'
        
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses:  gautamkrishnar/blog-post-workflow@master
        with:
          feed-url: https://manishyadav.dev/rss.xml
          max_post_count: "4"
